# Problem 4
# Find the largest palindrome made from the product of two 3-digit numbers.

# Notes:
# The range you are interested in is 100..999, not 1..999
# In general, you can avoid storing a bunch of large arrays, instead
# use loops and keep track of only the particular thing you're
# interested in.
# Methods which return a boolean usually end with a ?

# Method for checking if a number num is a palindrome
def palindrome?(num)
  s = num.to_s
  s == s.reverse
end

# Returns array of products generated by all the numbers in the arrays num1 and num2
max_so_far = 0
999.downto(100) do |num1|
  999.downto(100) do |num2|
    prod = num1 * num2
    max_so_far = prod if prod > max_so_far and palindrome? prod
  end
end

puts max_so_far
